#!/bin/sh

printf "Open AI client made using PySide6 qt\n"

if [ -f /.flatpak-info ]; then

    printf "Flatpak environment detected\n"
    printf "Running Inside Sandbox\n"
    /app/share/openai-client/main

else 
    printf "Not a flatpak environment\n"
    /usr/share/openai-client/main
fi


