#!/bin/sh

printf "QPlex\n"

if [ -f /.flatpak-info ]; then

    printf "Flatpak environment detected\n"
    printf "Running Inside Sandbox\n"
    /app/share/qplex/main

else 
    printf "Not a flatpak environment\n"
    /usr/share/qplex/main
fi


